version: '2'

services:test
    fhem:
        restart: always
        expose:
            - "8083"
            - "7072"
        ports:
            - "8083:8083"
            - "7072:7072"
        build: fhem
        privileged: truebhjhkjhhkjh
        volumes:
            - ./fhem/core/:/opt/fhem/
        networks:
            - fhem-network
        depends_on:
            - "mysql"
            - "mqtt"

    homebridge:
        restart: always
        image: oznu/homebridge
        volumes:
            - ./homebridge/config.json:/homebridge/config.json
            - ./homebridge/package.json:/homebridge/package.json
        environment:
            - TZ=Europe/Berlin
            - PGID=1000
            - PUID=1000
        network_mode: host
        depends_on:
            - "fhem"

    habridge:
        restart: always
        build: habridge
        network_mode: host

    mysql:
        restart: always
        expose:
            - "3306"
            - "33060"
        ports:
            - "3306:3306"
            - "33060:33060"
        image: mysql/mysql-server:5.7
        volumes:
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/fhem-init.sql
            - ./mysql/data:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        networks:
            - fhem-network

    mqtt:
        restart: always
        expose:
            - "1883"
            - "9001"
        ports:
            - "1883:1883"
            - "9001:9001"
        image: toke/mosquitto
        networks:
            - fhem-network
        volumes:
            - ./mqtt/config/:/mqtt/config/
            - ./mqtt/log/:/mqtt/log/
            - ./mqtt/data/:/mqtt/data/

    nodered:
        restart: always
        expose:
            - "1880"
        ports:
            - "1880:1880"
        image: nodered/node-red-docker:0.18.4
        volumes:
            - ./nodered/data/:/data/
        networks:
            - fhem-network
        depends_on:
            - "mqtt"

networks:
    fhem-network:
        driver: bridge
